### PR TITLE
OOM issues with openwebtext

### PR DESCRIPTION
**Pull request by bobbycxy**
1. Refrained from using DistributedSampler - took too long which means we no need .set_epoch. Hence, commented out the .set_epoch.
2. Used torch.randint to shuffle the selection of idx in dataset's __getitem__(self, idx).

### CODE REVIEW

**Comment by DylanASHillier** [comment]
hallalejuhah wimym

**Comment by bobbycxy** [comment]
> hallalejuhah wimym

hallelujah indeed brother

**Comment by bobbycxy** [comment]
if all good, i'll proceed to remove those commented lines in base_trainer.py

**Comment by DylanASHillier** [comment]
all good to me. I think check against the changes in my speed-mp branch to see if any of it is relevant

**Comment by DylanASHillier** [comment]
im kinda minded to do this from that branch since it is already a bit cleaner in some ways (but also way messier in other slol

**Comment by bobbycxy** [comment]
sure. I can try implementing the same thing on your branch and then see if it's working. otherwise I'll iteratively update and test them!

**Comment by DylanASHillier** [comment]
err check my branch and see what you think 
I just updated it to be basically same as yours I think but with all the fluff about single gpu which coudl remove

**Comment by DylanASHillier** [comment]
i guess main thing to carry over actually is just the context handling for run_step (whether to sync or not) let me test it

**Pull request closed without merging**
